import { GoogleGenAI, Modality } from '@google/genai';

// Helper to extract base64 data from a data URI
const getBase64Data = (dataUri: string): string => {
    return dataUri.split(',')[1];
};

// Function to edit an image based on a text prompt
export const editImage = async (base64Image: string, mimeType: string, prompt: string) => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: getBase64Data(base64Image),
                        mimeType: mimeType,
                    },
                },
                { text: prompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    const imagePart = response.candidates?.[0]?.content?.parts?.find(part => part.inlineData);
    if (imagePart && imagePart.inlineData) {
        return { base64: imagePart.inlineData.data, mimeType: imagePart.inlineData.mimeType };
    }
    throw new Error('No image was generated by the model.');
};
